service: angular-serverless-app

plugins:
  # - serverless-apigw-binary
  - serverless-offline
  # - serverless-api-compression
  # - serverless-associate-waf

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 10
  stage: dev
  region: us-east-1
  deploymentBucket:

package:
  excludeDevDependencies: true
  patterns:
    - '!src/**'
    - '!node_modules/**'
    - '!firebug-lite/**'
    - '!e2e/**'
    - '!coverage/**'
    - '!.angular/**'
    - '!.vscode/**'
    - node_modules/@vendia/**
    - node_modules/aws-serverless-express/**
    - node_modules/binary-case/**
    - node_modules/type-is/**
    - node_modules/media-typer/**
    - node_modules/mime-types/**
    - node_modules/mime-db/**

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 4000
  contentCompression: 1024
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY /{proxy+}
      - http: ANY /